import { savePlayers, saveMatches, saveTeam } from '@/lib/storage';
import type { Match, Player, Team, MatchPlayerStats, PlayerStats } from '@/types';

// Raw data from user
const rawPlayers = [
  { num: 1, pos: "GK", name: "Marcos", surname: "Fernández", age: 33, height: 189, weight: 84, nationality: "Spain" },
  { num: 13, pos: "GK", name: "Owen", surname: "Clarke", age: 27, height: 191, weight: 87, nationality: "England" },
  { num: 25, pos: "GK", name: "Tarek", surname: "Mansouri", age: 22, height: 187, weight: 82, nationality: "Morocco" },
  { num: 2, pos: "DF", name: "Lorenzo", surname: "Ricci", age: 29, height: 183, weight: 79, nationality: "Italy" },
  { num: 3, pos: "DF", name: "Jonas", surname: "Brandt", age: 26, height: 185, weight: 80, nationality: "Germany" },
  { num: 4, pos: "DF", name: "Adama", surname: "Diallo", age: 31, height: 188, weight: 85, nationality: "Senegal" },
  { num: 5, pos: "DF", name: "Nikola", surname: "Petrović", age: 28, height: 190, weight: 88, nationality: "Serbia" },
  { num: 6, pos: "DF", name: "Sébastien", surname: "Moreau", age: 24, height: 182, weight: 77, nationality: "France" },
  { num: 23, pos: "DF", name: "Callum", surname: "Hughes", age: 21, height: 181, weight: 75, nationality: "Wales" },
  { num: 7, pos: "MF", name: "Rafaelo", surname: "Costa", age: 27, height: 178, weight: 73, nationality: "Brazil" },
  { num: 8, pos: "MF", name: "Dimitri", surname: "Stavros", age: 30, height: 180, weight: 76, nationality: "Greece" },
  { num: 10, pos: "MF", name: "Javi", surname: "Ortega", age: 25, height: 176, weight: 71, nationality: "Spain" },
  { num: 14, pos: "MF", name: "Cian", surname: "O'Brien", age: 23, height: 179, weight: 74, nationality: "Ireland" },
  { num: 16, pos: "MF", name: "Emeka", surname: "Okafor", age: 26, height: 182, weight: 78, nationality: "Nigeria" },
  { num: 18, pos: "MF", name: "Luca", surname: "Bianchi", age: 29, height: 177, weight: 72, nationality: "Italy" },
  { num: 19, pos: "MF", name: "Artur", surname: "Wiśniewski", age: 24, height: 181, weight: 76, nationality: "Poland" },
  { num: 9, pos: "FW", name: "Théo", surname: "Lambert", age: 28, height: 184, weight: 82, nationality: "France" },
  { num: 11, pos: "FW", name: "Dani", surname: "Suárez", age: 26, height: 176, weight: 72, nationality: "Argentina" },
  { num: 15, pos: "FW", name: "Kofi", surname: "Asante", age: 23, height: 179, weight: 74, nationality: "Ghana" },
  { num: 17, pos: "FW", name: "Ryo", surname: "Tanaka", age: 25, height: 174, weight: 69, nationality: "Japan" },
  { num: 20, pos: "FW", name: "Erik", surname: "Lindström", age: 22, height: 183, weight: 78, nationality: "Sweden" },
  { num: 21, pos: "FW", name: "Mateo", surname: "Vargas", age: 30, height: 177, weight: 75, nationality: "Colombia" },
  { num: 22, pos: "FW", name: "Bashir", surname: "Al-Rashid", age: 24, height: 180, weight: 76, nationality: "Saudi Arabia" },
];

const rawMatches = [
  {
    id: 1, date: "2024-08-15", opponent: "Atletico Madrid", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 1, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 1, secondAssists: 0, yellowCards: 1, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 1, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 78 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 1, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 82 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 12 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 20 },
    ],
  },
  {
    id: 2, date: "2024-08-22", opponent: "Real Sociedad", venue: "Anoeta Stadium",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 1, result: "D",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 1, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 85 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 5 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 5 },
    ],
  },
  {
    id: 3, date: "2024-08-29", opponent: "Sevilla FC", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 3, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 4, date: "2024-09-05", opponent: "Valencia CF", venue: "Mestalla Stadium",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 2, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 5, date: "2024-09-12", opponent: "Real Madrid", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 1, goalsAgainst: 3, result: "L",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 6, date: "2024-09-19", opponent: "Villarreal CF", venue: "Estadio de la Cerámica",
    venueType: "away", formation: "4-3-3", goalsFor: 2, goalsAgainst: 0, result: "W",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 7, date: "2024-09-26", opponent: "Athletic Bilbao", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 1, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 8, date: "2024-10-03", opponent: "Celta Vigo", venue: "Abanca-Balaídos",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 1, result: "D",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 9, date: "2024-10-10", opponent: "Getafe CF", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 3, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 10, date: "2024-10-17", opponent: "Real Betis", venue: "Estadio Benito Villamarín",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 1, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 11, date: "2024-10-24", opponent: "Osasuna", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 12, date: "2024-10-31", opponent: "Girona FC", venue: "Montilivi",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 2, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 13, date: "2024-11-07", opponent: "Rayo Vallecano", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 3, goalsAgainst: 1, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 14, date: "2024-11-14", opponent: "Mallorca", venue: "Visit Mallorca Estadi",
    venueType: "away", formation: "4-3-3", goalsFor: 2, goalsAgainst: 0, result: "W",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 15, date: "2024-11-21", opponent: "Las Palmas", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 1, goalsAgainst: 1, result: "D",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 16, date: "2024-11-28", opponent: "Alavés", venue: "Mendizorroza",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 0, result: "D",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 17, date: "2024-12-05", opponent: "Barcelona", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 1, goalsAgainst: 4, result: "L",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 18, date: "2024-12-12", opponent: "Espanyol", venue: "RCDE Stadium",
    venueType: "away", formation: "4-3-3", goalsFor: 3, goalsAgainst: 1, result: "W",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 19, date: "2024-12-19", opponent: "Leganés", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 20, date: "2024-12-26", opponent: "Valladolid", venue: "José Zorrilla",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 1, result: "D",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 21, date: "2025-01-02", opponent: "Atletico Madrid", venue: "Wanda Metropolitano",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 3, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 22, date: "2025-01-09", opponent: "Real Sociedad", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 1, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 23, date: "2025-01-16", opponent: "Sevilla FC", venue: "Ramón Sánchez-Pizjuán",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 2, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 24, date: "2025-01-23", opponent: "Valencia CF", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 3, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 25, date: "2025-01-30", opponent: "Real Madrid", venue: "Santiago Bernabéu",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 4, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 26, date: "2025-02-06", opponent: "Villarreal CF", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 1, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 27, date: "2025-02-13", opponent: "Athletic Bilbao", venue: "San Mamés",
    venueType: "away", formation: "4-3-3", goalsFor: 1, goalsAgainst: 1, result: "D",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 28, date: "2025-02-20", opponent: "Celta Vigo", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 3, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 29, date: "2025-02-27", opponent: "Getafe CF", venue: "Coliseum Alfonso Pérez",
    venueType: "away", formation: "4-3-3", goalsFor: 0, goalsAgainst: 1, result: "L",
    squad: [13, 2, 5, 6, 3, 14, 8, 18, 17, 9, 20],
    subs: [1, 7, 10],
    playerStats: [
      { playerNum: 13, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 6, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 14, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 18, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 20, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 10, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
  {
    id: 30, date: "2025-03-06", opponent: "Real Betis", venue: "Estadio San Mames",
    venueType: "home", formation: "4-3-3", goalsFor: 2, goalsAgainst: 0, result: "W",
    squad: [1, 4, 5, 2, 3, 7, 8, 10, 11, 9, 15],
    subs: [13, 16, 17],
    playerStats: [
      { playerNum: 1, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 4, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 5, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 2, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 3, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 7, goals: 0, assists: 1, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 8, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 10, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 11, goals: 1, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 9, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 15, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 90 },
      { playerNum: 16, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
      { playerNum: 17, goals: 0, assists: 0, secondAssists: 0, yellowCards: 0, redCards: 0, minutesPlayed: 0 },
    ],
  },
];

function posToPositions(pos: string): string[] {
  switch (pos) {
    case 'GK': return ['Goalkeeper'];
    case 'DF': return ['Defender'];
    case 'MF': return ['Midfielder'];
    case 'FW': return ['Forward'];
    default: return ['Unknown'];
  }
}

export function populateRealisticData(): void {
  // Create players
  const players: Player[] = rawPlayers.map(p => ({
    id: `player-${p.num}`,
    firstName: p.name,
    lastName: p.surname,
    age: p.age,
    nationality: p.nationality,
    height: p.height,
    weight: p.weight,
    positions: posToPositions(p.pos),
    jerseyNumber: p.num.toString(),
    stats: {
      goals: 0,
      assists: 0,
      secondAssists: 0,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 0,
      matchesPlayed: 0,
    },
  }));

  // Create player ID map
  const playerIdByNum = new Map(players.map(p => [parseInt(p.jerseyNumber!), p.id]));

  // Create matches
  const matches: Match[] = rawMatches.map(m => ({
    id: m.id.toString(),
    opponent: m.opponent,
    date: m.date,
    location: m.venue,
    type: m.venueType as 'home' | 'away' | 'neutral',
    status: 'completed',
    score: {
      team: m.goalsFor,
      opponent: m.goalsAgainst,
    },
    formation: m.formation,
    playerStats: m.playerStats.reduce((acc, stat) => {
      const playerId = playerIdByNum.get(stat.playerNum);
      if (playerId) {
        acc[playerId] = {
          goals: stat.goals,
          assists: stat.assists,
          secondAssists: stat.secondAssists,
          yellowCards: stat.yellowCards,
          redCards: stat.redCards,
          minutesPlayed: stat.minutesPlayed,
        };
      }
      return acc;
    }, {} as { [playerId: string]: MatchPlayerStats }),
  }));

  // Aggregate player stats from matches
  const playerStatsMap = new Map<string, PlayerStats>();
  matches.forEach(match => {
    if (match.playerStats) {
      Object.entries(match.playerStats).forEach(([playerId, stats]) => {
        if (!playerStatsMap.has(playerId)) {
          playerStatsMap.set(playerId, {
            goals: 0,
            assists: 0,
            secondAssists: 0,
            yellowCards: 0,
            redCards: 0,
            minutesPlayed: 0,
            matchesPlayed: 0,
          });
        }
        const current = playerStatsMap.get(playerId)!;
        current.goals += stats.goals;
        current.assists += stats.assists;
        current.secondAssists += stats.secondAssists;
        current.yellowCards += stats.yellowCards;
        current.redCards += stats.redCards;
        current.minutesPlayed += stats.minutesPlayed;
        current.matchesPlayed += 1;
      });
    }
  });

  // Update player stats
  players.forEach(p => {
    const stats = playerStatsMap.get(p.id);
    if (stats) {
      p.stats = stats;
    }
  });

  // Create team
  const sampleTeam: Team = {
    id: 'sample-team',
    name: 'Sample FC',
    formation: '4-3-3',
    foundedDate: new Date().toISOString(),
    abbreviation: 'SFC',
    theme: 'dark',
    colors: {
      primary: '#7c3aed',
      secondary: '#0f172a',
    },
  };

  console.log(`Loading sample players: ${players.length}`);
  console.log(`Loading matches: ${matches.length}`);

  console.log('Saving sample team, players, and matches to storage...');
  saveTeam(sampleTeam);
  savePlayers(players);
  saveMatches(matches);

  console.log('Sample data loaded.');
}
